### ISSUE TITLE
design mission end

### ISSUE THREAD

**Issue by milivojm** [ArmA3Pro/mission-pack#11]
Design mission end conditions. At the moment mission continues forever.

**Comment by milivojm** [comment]
@chypsa - here is a try. Let's suppose NATO is attacking Chalkia and CSAT and AAF are defending it (initially). How about we add another 2 cities that follow after Chalkia has been seized but without AAF help. 

For example:

NATO seize Chalkia. New task is assigned to CSAT - defend the town of X, NATO gets attack the town of X. If NATO manages to seize X, focus is moved to last objective Y. If Y is seized, game is over. CSAT would need to defend for 2 hours and if NATO fails to achieve it's objectives, CSAT wins.

That would influence force ratio and we'd need to strengthen attack forces over defending CSAT forces.

**Comment by chypsa** [comment]
I think keeping things to a minimum of complication is best at the moment. People tend to have a hard time reorganising after an initial breach occurs anyway and since the offensive side is on the offense and has momentum, it's likely the rest of the mission would just be waiting out the inevitable end.

For this to work, I think it would be necessary for the respawn to be triggered as soon as an objective falls as that _might_ give the defenders time to reorganize.

But, certainly, we can try it at some point.
