### ISSUE TITLE
tweak revive and medical settings 

### ISSUE THREAD

**Issue by milivojm** [ArmA3Pro/mission-pack#15]
At the moment players come alive on their own way too often, without the need for a medical assistance. Begs the question: should we disable revive, how does revive behave when "prevent instant death" setting is disabled etc. 

Can you please investigate.

**Comment by chypsa** [comment]
From what I've gathered, prevent instant death is only meant to place the unit unconscious if they take a single-shot-kill, like the AI sometimes do in stupid situations (500m, through the bushes, headshot).

To my knowledge, this function is _not _needed_ in order to use revive. We can test this tonight if you like.

See point 2.1.4. on the link.

http://ace3mod.com/wiki/feature/medical-system.html#revive-basic-medical

Obvious problem is that you can't kill a unit in UC state, they can only die due to a timer, which is not the functionality we want, I think. Will examine further tonight.

**Comment by milivojm** [comment]
Yes, it's kind of stupid. I got shot in the head last night and resurrected magically by myself without doing anything. I think we should remove Revive module as this kind of functionality is not good for PvP. Imagine having to guard someone's corps for 3 minutes just to make sure he is properly dead - no Barney cross fingers!

The question now is:

- does the unit go unconscious in basic medical if _prevent instant death_ is disabled?
- if it goes unconscious - can it be cured without _revive_ module enabled?

**Comment by chypsa** [comment]
Yes, but you can't have unlimited round duration and no revive. I vote we test the shit out of the revive module until we find something that's not idiotic :)

**Comment by milivojm** [comment]
Well, I don't think we should allow reviving people shot in the head. Prevent instant death should be disabled definitely. 

Have a look at the following [discussion](https://github.com/acemod/ACE3/issues/839).

**Comment by chypsa** [comment]
I do agree we should disable Prevent instant death, especially for TvT, but I'd leave Revive enabled. It remains to be seen what happens ingame when we combine modules and settings.

I've read the topic, that's why I wrote "Obvious problem is that you can't kill a unit in UC state, they can only die due to a timer, which is not the functionality we want, I think. Will examine further tonight." Now it's just a question if that also happens if we remove PiD, but leave Revive.

**Comment by milivojm** [comment]
Revive time increase to 20 seconds, unit is in revive state for 240 seconds (can force respawn).
